import Head from "next/head";
import { IndexSection } from "../components/IndexSection";

export default function IndexPage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<IndexSection />
		</>
	);
}
